services:
  - type: web
    name: project-management-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGO_URI
        sync: false
      - key: SECRET
        sync: false 